-- Migration: Meal Planning and Family Nutrition
-- Extends nutrition support for holistic meal planning, family meals, and grocery lists

-- ============================================================================
-- EXTEND USER PREFERENCES WITH MEAL PLANNING
-- ============================================================================
ALTER TABLE user_preferences
ADD COLUMN IF NOT EXISTS favorite_foods TEXT[],           -- Foods user loves
ADD COLUMN IF NOT EXISTS disliked_foods TEXT[],           -- Foods to avoid
ADD COLUMN IF NOT EXISTS cooking_skill TEXT DEFAULT 'intermediate'
    CHECK (cooking_skill IN ('beginner', 'intermediate', 'advanced')),
ADD COLUMN IF NOT EXISTS weeknight_cooking_time INTEGER DEFAULT 30,  -- Minutes available for weeknight cooking
ADD COLUMN IF NOT EXISTS weekend_cooking_time INTEGER DEFAULT 60,    -- Minutes for weekend cooking
ADD COLUMN IF NOT EXISTS batch_cooking_day TEXT,          -- Preferred day for batch cooking (e.g., 'sunday')
ADD COLUMN IF NOT EXISTS grocery_store_preference TEXT,   -- Primary grocery store
ADD COLUMN IF NOT EXISTS budget_level TEXT DEFAULT 'moderate'
    CHECK (budget_level IN ('budget', 'moderate', 'premium'));

-- ============================================================================
-- FAMILY MEMBERS
-- For meal planning that accounts for the whole family
-- ============================================================================
CREATE TABLE IF NOT EXISTS family_members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    name TEXT NOT NULL,
    relationship TEXT NOT NULL CHECK (relationship IN ('spouse', 'child', 'parent', 'other')),
    age_category TEXT CHECK (age_category IN ('infant', 'toddler', 'child', 'teen', 'adult', 'senior')),

    -- Dietary needs
    dietary_restrictions TEXT[],      -- e.g., ['gluten-free', 'dairy-free']
    allergies TEXT[],                 -- Food allergies

    -- Preferences (especially for kids)
    favorite_foods TEXT[],
    disliked_foods TEXT[],
    picky_level TEXT DEFAULT 'normal' CHECK (picky_level IN ('not_picky', 'normal', 'picky', 'very_picky')),

    notes TEXT,
    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_family_members_user ON family_members(user_id, is_active);

-- ============================================================================
-- MEAL PLANS
-- Weekly meal plans generated by the agent
-- ============================================================================
CREATE TABLE IF NOT EXISTS meal_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Plan period
    week_start_date DATE NOT NULL,

    -- Training context used for plan
    training_phase TEXT,
    weekly_mileage DECIMAL(5,1),
    has_long_run_day TEXT,           -- e.g., 'saturday'

    -- Plan status
    status TEXT DEFAULT 'active' CHECK (status IN ('draft', 'active', 'completed', 'archived')),

    -- Generation metadata
    generated_by TEXT DEFAULT 'meal-planner-agent',
    athlete_needs_summary TEXT,       -- Summary of nutritional needs used

    notes TEXT,
    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(user_id, week_start_date)
);

CREATE INDEX IF NOT EXISTS idx_meal_plans_user_date ON meal_plans(user_id, week_start_date DESC);

-- ============================================================================
-- PLANNED MEALS
-- Individual meals within a meal plan
-- ============================================================================
CREATE TABLE IF NOT EXISTS planned_meals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    meal_plan_id UUID NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Meal details
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
    meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack', 'pre_workout', 'post_workout')),

    -- The meal itself
    name TEXT NOT NULL,               -- e.g., "Salmon with sweet potato and broccoli"
    description TEXT,
    prep_time_minutes INTEGER,
    cook_time_minutes INTEGER,

    -- Family context
    is_family_meal BOOLEAN DEFAULT TRUE,
    athlete_modifications TEXT,       -- How to adjust for athlete (e.g., "add extra rice")
    kid_modifications TEXT,           -- How to adjust for kids (e.g., "serve sauce on side")

    -- Training context
    training_relevance TEXT,          -- e.g., "Pre-long run carb loading"

    -- Recipe link (optional)
    recipe_id UUID REFERENCES saved_recipes(id) ON DELETE SET NULL,

    -- Status
    completed BOOLEAN DEFAULT FALSE,
    completion_notes TEXT,

    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_planned_meals_plan ON planned_meals(meal_plan_id);
CREATE INDEX IF NOT EXISTS idx_planned_meals_user_day ON planned_meals(user_id, day_of_week);

-- ============================================================================
-- SAVED RECIPES
-- User's recipe collection with athlete adaptations
-- ============================================================================
CREATE TABLE IF NOT EXISTS saved_recipes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Recipe basics
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN (
        'quick_weeknight',
        'batch_cooking',
        'special_occasion',
        'kid_favorite',
        'athlete_recovery',
        'pre_workout',
        'other'
    )),

    -- Recipe details
    servings INTEGER DEFAULT 4,
    prep_time_minutes INTEGER,
    cook_time_minutes INTEGER,

    -- Content
    ingredients JSONB NOT NULL,       -- Array of { item, quantity, unit, notes }
    instructions JSONB NOT NULL,      -- Array of step strings

    -- Athlete-specific
    athlete_adaptation TEXT,          -- How to modify for athlete
    nutrition_notes TEXT,
    is_good_pre_workout BOOLEAN DEFAULT FALSE,
    is_good_post_workout BOOLEAN DEFAULT FALSE,
    is_carb_heavy BOOLEAN DEFAULT FALSE,
    is_protein_heavy BOOLEAN DEFAULT FALSE,

    -- Family-specific
    kid_adaptation TEXT,              -- How to modify for kids
    kid_friendly_rating INTEGER CHECK (kid_friendly_rating >= 1 AND kid_friendly_rating <= 5),

    -- Tags for searching
    tags TEXT[],                      -- e.g., ['high-protein', 'one-pot', 'freezer-friendly']

    -- Source
    source_url TEXT,
    source_notes TEXT,

    -- Usage tracking
    times_made INTEGER DEFAULT 0,
    last_made_date DATE,
    is_favorite BOOLEAN DEFAULT FALSE,

    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_saved_recipes_user ON saved_recipes(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_recipes_category ON saved_recipes(user_id, category);
CREATE INDEX IF NOT EXISTS idx_saved_recipes_tags ON saved_recipes USING gin(tags);

-- ============================================================================
-- GROCERY LISTS
-- Generated shopping lists from meal plans
-- ============================================================================
CREATE TABLE IF NOT EXISTS grocery_lists (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    meal_plan_id UUID REFERENCES meal_plans(id) ON DELETE SET NULL,

    -- List details
    for_week_of DATE NOT NULL,
    name TEXT DEFAULT 'Weekly Groceries',

    -- Status
    status TEXT DEFAULT 'active' CHECK (status IN ('draft', 'active', 'shopping', 'completed')),

    -- Store info
    primary_store TEXT,
    estimated_total_low DECIMAL(8,2),
    estimated_total_high DECIMAL(8,2),
    actual_total DECIMAL(8,2),

    -- Completion tracking
    items_total INTEGER DEFAULT 0,
    items_purchased INTEGER DEFAULT 0,
    shopping_started_at TIMESTAMP WITH TIME ZONE,
    shopping_completed_at TIMESTAMP WITH TIME ZONE,

    notes TEXT,
    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_grocery_lists_user ON grocery_lists(user_id, status);

-- ============================================================================
-- GROCERY LIST ITEMS
-- Individual items on a grocery list
-- ============================================================================
CREATE TABLE IF NOT EXISTS grocery_list_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    grocery_list_id UUID NOT NULL REFERENCES grocery_lists(id) ON DELETE CASCADE,

    -- Item details
    item_name TEXT NOT NULL,
    quantity TEXT,                    -- e.g., "2 lbs", "1 bunch", "6 count"

    -- Organization
    section TEXT NOT NULL CHECK (section IN (
        'produce',
        'proteins',
        'dairy',
        'grains',
        'pantry',
        'frozen',
        'athlete_specific',
        'other'
    )),

    -- Context
    for_meals TEXT[],                 -- Which meals this item is for
    is_athlete_specific BOOLEAN DEFAULT FALSE,
    notes TEXT,

    -- Shopping
    is_purchased BOOLEAN DEFAULT FALSE,
    purchased_at TIMESTAMP WITH TIME ZONE,
    actual_price DECIMAL(6,2),
    substituted_with TEXT,

    sort_order INTEGER DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_grocery_list_items_list ON grocery_list_items(grocery_list_id, section);

-- ============================================================================
-- BATCH COOKING PLANS
-- Plans for meal prep sessions
-- ============================================================================
CREATE TABLE IF NOT EXISTS batch_cooking_plans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    meal_plan_id UUID REFERENCES meal_plans(id) ON DELETE SET NULL,

    -- Session details
    planned_date DATE NOT NULL,
    total_time_minutes INTEGER,

    -- Status
    status TEXT DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'completed', 'skipped')),

    -- Items to prep (stored as JSON for flexibility)
    items JSONB NOT NULL,             -- Array of { item, quantity, prep_order, active_time, storage, used_for, keeps_days }

    -- Shopping needs
    additional_shopping JSONB,        -- Any extra ingredients needed

    -- Completion
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    actual_duration_minutes INTEGER,
    completion_notes TEXT,

    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_batch_cooking_plans_user ON batch_cooking_plans(user_id, planned_date);
